### ISSUE TITLE
Better Text-Formatting of Output.

### ISSUE THREAD

**Issue by rahulnegi20** [rahulnegi20/tdict#1]
### A better textual representation of output by improving text-formatting in any way possible. 
- Textual animations.
- Designed text etc.

**Comment by atTheShikhar** [comment]
You can use [simple-chalk](https://pypi.org/project/simple-chalk/) to making the text formatting interesting.

**Comment by SineshX** [comment]
I can format it like windows branch if u like 😁

![image](https://user-images.githubusercontent.com/48027382/137636653-ceb3a6b0-568e-4ae0-b1b1-8b5afa893520.png)

**Comment by rahulnegi20** [comment]
yeah sure it does looks nice and more readable.
