### ISSUE TITLE
Argparse instead of input

### ISSUE THREAD

**Issue by ravish0007** [rahulnegi20/tdict#3]
I believe it will be better to run this program with command line arguments, I always wanted a tool like this, hope I can contribute to this.

**Comment by rahulnegi20** [comment]
It's a command line tool you have to provide the word with the name like `tdict <word>`. You can check the readme file i have provided the example there.
If it is not what you meant please elaborate.

Yeah please contribution is always appreciated! Thanks.

**Comment by ravish0007** [comment]
Oh okay, I saw that tdict now I was thinking it'll be good to eliminate tdict and put that into the script itself. What do you think of this ?

**Comment by rahulnegi20** [comment]
tdict is like a bash command here, to call the dict.py program. How we're supposed to call the program without that? If that's possible we can implement that for sure!

**Comment by SineshX** [comment]
Hey! I think I can fix this issue. Can you assign it to me?
like : 
- give user both option argument  passing 
 - or user input 
 
 let say by mistake if we just call tdict 
 it will ask for input , else search tdict myWord

**Comment by rahulnegi20** [comment]
> Hey! I think I can fix this issue. Can you assign it to me? like :
> 
> * give user both option argument  passing
> * or user input
> 
> let say by mistake if we just call tdict it will ask for input , else search tdict myWord

Yeah sure.

**Comment by rahulnegi20** [comment]
This issue has been solved by @SineshX, hence I am closing this issue. 
Thanks for participation.
