### ISSUE TITLE
Feature  Request : Calling tdict with or without argument.

### ISSUE THREAD

**Issue by rahulnegi20** [rahulnegi20/tdict#5]
let say by mistake if we just call tdict
it will ask for input , else search tdict <word>

**Comment by SineshX** [comment]
assign me :)

**Comment by SineshX** [comment]
![image](https://user-images.githubusercontent.com/48027382/136022999-da0a3d65-2a73-48db-ae45-8f8c4d0f53cf.png)

done , I can also create a branch for windows implement global calling and update readme file  too :)

**Comment by rahulnegi20** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/48027382/136022999-da0a3d65-2a73-48db-ae45-8f8c4d0f53cf.png)
> 
> done , I can also create a branch for windows implement global calling and update readme file too :)

Sounds awesome!
